### ISSUE TITLE
object 'channel_id' doesn't exist

### ISSUE THREAD

**Issue by damientully** [nanoporetech/pod5-file-format#12]
Hello,

When trying to convert fast5 into pod5 using pod5-convert-from-fast5 I get the following error message relating to the channel_id. Any suggestions or help? 

```
Error in file Raw/0/AllenMiseq2_20170425_FN_MN19868_mux_scan_sample_id_37726_ch507_read77_strand.fast5: "Unable to open object (object 'channel_id' doesn't exist)"
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pod5_format_tools/pod5_convert_from_fast5.py", line 157, in get_reads_from_files
    channel_id = inp[key]["channel_id"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.8/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
```

**Comment by jorj1988** [comment]
Hi @damientully,

From the filename it looks like your file is a single read fast5 file, which nanopore tools stopped producing some time ago.

The pod5 convertor does not accept this format as input, and instead needs you to convert these files (one read per fast5 file) to our grouped file format (many reads per fast5 file). The pod5 file convertor can then consume the multi read fast5 file format.

This project https://github.com/nanoporetech/ont_fast5_api contains tools to migrate your dataset to multi fast5 files.

I will ensure as a follow up to this ticket the message from the convertor tool is clearer in future, and points users to this multi fast5 convertor resource.

Thanks,
- George

**Comment by jorj1988** [comment]
The error message for this issue is improved in the current release, so I am going to retire this issue.

- George
