### ISSUE TITLE
pod5 breaks with new numpy 2.0.0

### ISSUE THREAD

**Issue by Psy-Fer** [nanoporetech/pod5-file-format#133]
## Issue Description

When trying to use pod5 after installing numpy v2.0.0 I get a bunch of errors

Any ideas on how to fix this?

Cheers
James

## Logs
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/src/blue_crab.py", line 16, in <module>
    import pod5 as p5
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/pod5/__init__.py", line 17, in <module>
    from .api_utils import (
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/pod5/api_utils.py", line 11, in <module>
    import pyarrow as pa
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/repos/blue-crab/blue-crab-np-test/bin/blue-crab", line 5, in <module>
    from src.blue_crab import main
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/src/blue_crab.py", line 16, in <module>
    import pod5 as p5
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/pod5/__init__.py", line 17, in <module>
    from .api_utils import (
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/pod5/api_utils.py", line 11, in <module>
    import pyarrow as pa
  File "/repos/blue-crab/blue-crab-np-test/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/lib.pyx", line 36, in init pyarrow.lib
ImportError: numpy.core.multiarray failed to import
```

## Specifications
```
Package         Version
--------------- -------
blue-crab       0.1.0
h5py            3.10.0
iso8601         2.1.0
lib_pod5        0.3.10
more-itertools  10.3.0
numpy           2.0.0
packaging       24.1
pip             24.0
pod5            0.3.10
polars          0.20.31
pyarrow         14.0.2
pyslow5         1.2.0b0
pytz            2024.1
setuptools      59.6.0
tqdm            4.66.4
vbz-h5py-plugin 1.0.1

python 3.10.12
platform: pop!_OS linux/ubuntu
```

**Comment by 0x55555555** [comment]
Hi James,

We will take a look at this!

Thanks,
- George

**Comment by tamalarafat** [comment]
I solved the issue by downgrading numpy from version 2.0 to 1.26.4.

Although the error "ImportError: numpy.core.multiarray failed to import" was resolved, I am now encountering a new error while trying to convert my ".pod5" files to ".fast5" files.

The error I am getting now is:
"
cmd: pod5 convert to_fast5 *.pod5 --output pod5_to_fast5/
  
error: File "<stdin>", line 1
pod5 convert to_fast5 *.pod5 --output pod5_to_fast5/
     ^^^^^^^
SyntaxError: invalid syntax
"

Any idea?

**Comment by 0x55555555** [comment]
Hi @tamalarafat ,

It looks like you may be running bash commands inside a python file - the line you have: 

```bash
>  pod5 convert to_fast5 *.pod5 --output pod5_to_fast5/
```

Is a bash command, i believe.

We have an internal pod5 build which is numpy 2.0 compatible, due out shortly.

Thanks,
- George

**Comment by Psy-Fer** [comment]
Great to hear 😁

**Comment by tamalarafat** [comment]
Thanks, George!

**Comment by 0x55555555** [comment]
Hi @Psy-Fer,

`0.3.11` is now out, and is compatible with numpy 2.0 - please let us know if you have any issues.

Thanks,
- George

**Comment by Psy-Fer** [comment]
Okay i tried it out and it all works!

We also released new pyslow5 wheels with a new version which also fixed all of our problems.

So all sorted. Thanks George.

James
