### ISSUE TITLE
pod5 convert fast5 -> 100% of reads converted but process not finished when converting bigger datasets

### ISSUE THREAD

**Issue by gwl2** [nanoporetech/pod5-file-format#31]
I use the following line in a bash script to convert my fast5 files to pod5

> pod5 convert fast5 *.fast5 --output converted.pod5

In general, it works as expected. However, if I run the bash script on bigger data sets, conversion starts, reaches 100% and nothing happens. The next parts of my script are not executed. If I use the same script on a "smaller" data set, the conversion and the whole script finishes as expected.
Interestingly, if I terminate the conversion with "ctrl + C" when it reaches 100% the other steps are getting executed.

Here is the out put of the terminal, when killing the conversion:
> Converting 206 Fast5s: 100%|#######| 821696/821696 [01:40<00:00, 8144.87Reads/s]
^CException ignored in atexit callback: <function _exit_function at 0x7f91e832ecb0>
Traceback (most recent call last):
  File "/home/nanopore/software/anaconda3/lib/python3.10/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/nanopore/software/anaconda3/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/nanopore/software/anaconda3/lib/python3.10/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/nanopore/software/anaconda3/lib/python3.10/multiprocessing/queues.py", line 199, in _finalize_join
    thread.join()
  File "/home/nanopore/software/anaconda3/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/nanopore/software/anaconda3/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:

Of note, the same happens if I only run the command above in a terminal on its own. It finished for small data sets but not for the bigger ones, although both reach 100%. I was waiting for an hour and nothing happened.

**Comment by jorj1988** [comment]
Hi @gwl2 ,

Is this on the latest release? This sounds very similar to a bug we already fixed.

Thanks,
- George

**Comment by gwl2** [comment]
No, I use the version that is included in duplex_tools. That version lags behing it seems. I will report the issue there.

**Comment by gwl2** [comment]
Just one more question. As written above, I "solved" the problem by pressing "ctrl +c" to stop the conversion once it reached 100% and used the obained pod5. Could there be an issue with this file? Do I have to reconvert with the newest version of pod5?

**Comment by jorj1988** [comment]
What we found as part of the other issue was the hang was in python's threading code, and all the conversion was complete.

So the files should be fine as is.

- George
